python_script:
  build: ./Build_docker_test
  links:
    - redis
  ports:
    - "8080"
  env_file:
    - secrets.env
  environment: 
    - COW=${PASSWORD}
  volumes:
    - ./:/app

redis:
  image: redis
  ports:
    - "6379"