version: "3.8"
services:
  pythcript:
    build:
      context: ./second_folder/ #github URL goes here
      dockerfile: Dockerfile.dockerfile
    image: pie_test:5 #create name for image here
    links:
      - redis
    ports:
      - 8080:8080
    env_file:
      - secrets.env
    volumes:
      - ./second_folder:/app

  redis:
    image: redis
    ports:
      - "6379"